### PR TITLE
feat: Implemented semantic release

### PR DESCRIPTION
**Pull request by seebeen**
## The Issue

Current release flow is manual. Since the semantic commits are already in place - it can be vastly improved by using an automated release process depending on the commit type.

Having manual semantic versioning can cause unneeded major / minor version incrementation, and can cause wild release number jumps depending on the current commiter, working team, and personal style / coding preference.

The previous release flow has various steps which are manual and which are used to check the next version, analyze commits, and do all of the stuff a single npm package does automatically, in a simple, reliable and consistent manner.

## How This PR Solves The Issue

Implements a semantic release flow with automatic changelog generation, and major / major.minor versioning for the marketplace action.

Using the `semantic-release` package automates the whole package release workflow including:
 * determining the next version number
 * generating the release notes
 * publishing the package

By using semantic versioning, there is no relation between human emotion and version numbers. Changelog generation is automatic, standardized, and links everything properly in various ways.
It also does comments on PRs, Issues, and discussions.

This PR simplifies the action development, and reduces maintenance time.

## Manual Testing Instructions

None needed

## Automated Testing Overview

Merging this pr will automatically bump the minor version.

## Release/Deployment Notes

Will improve deployment further on.

### CODE REVIEW

**Comment by rfay** [comment]
I think you'd have more success with things like this if you opened an issue first asking whether this would be welcome. When you just dive in with a PR you're assuming that people will automatically agree with your view of the world.

Then, when you make a PR, consider it your job to carefully explain why you're doing it, what the effects are, and why you think it's important. None of those things are done here. 

Just because you know what you think should happen doesn't mean that others with either understand what you think or agree with it.

**Comment by seebeen** [comment]
> I think you'd have more success with things like this if you opened an issue first asking whether this would be welcome. When you just dive in with a PR you're assuming that people will automatically agree with your view of the world.
> 
> Then, when you make a PR, consider it your job to carefully explain why you're doing it, what the effects are, and why you think it's important. None of those things are done here.
> 
> Just because you know what you think should happen doesn't mean that others with either understand what you think or agree with it.

Edited the description

**Comment by rfay** [comment]
Far better, thanks.

I have in fact made a mistake with a release version on DDEV. It was unfortunate. Intended v1.20.1 and did v1.21.1 IIRC

**Comment by julienloizelet** [comment]
Thank you for this PR and for introducing me to this semantic-release package.

I have several reasons for thinking that the current release process would have a hard time being replaced by a fully automatic one.

But it's an interesting subject, so I think I'll test this approach on a few of my personal projects.

And now, a few points that I think need to be discussed if we are to move in this direction: 

1)  > the semantic commits are already in place

Well, there is a `.githooks` folder that aims to be used as a template for a `commit-msg` hook but we did not implemented any check to see if all commits respect the convention format. Could be something interesting to work on... Should be possible to check commit message for a pull request with some GitHub action but I don't know how to prevent badly formatted message for a direct push, for example.

 2) > there is no relation between human emotion and version numbers

To determine the next version number , I base myself on https://semver.org/spec/v2.0.0.html

a) One of the most important points is to define, as explicitly as possible, what the public API is. In the case of this project, I've defined the [public API as being determined solely by the `action.yaml` file](https://github.com/ddev/github-action-add-on-test/blob/main/CHANGELOG.md#public-api). This means that we need to be able to consider only modifications to this file for release changes: we need to be able to exclude commits to files not covered by the public API (docs, .githooks and tests folder, etc.).
  
    
 b) It's true that with every release, I have to ask myself whether it's just a fix without breaking change (patch), a modification/addition without breaking change (minor), or a breaking change (major): it's a human decision, with all the risks that entails.

 BUT, as far as I can read here: https://www.npmjs.com/package/semantic-release#how-does-it-work , semantic-release is using commit messages to determine the next release number. and these commit messages will have been written by humans ... For example, the responsibility for writing BREAKING CHANGE in the footer of the commit message will have been taken by a human; and I don't see much difference between that decision and the one I have to take now, every time I prepare to create a release.
    
 
3) To conclude, but this is more of a personal opinion, unfortunately too suggestive, I'm basing the changelog on this: https://keepachangelog.com/en/1.1.0/ and I like the guiding principle: "Changelogs are for humans, not machines.".
So I'm not too keen on seeing a list of commit messages in a changelog (a link with a version comparison seems sufficient for those interested in the details of each commit).


Thanks

**Comment by julienloizelet** [comment]
> I have in fact made a mistake with a release version on DDEV. It was unfortunate. Intended v1.20.1 and did v1.21.1 IIRC

I remember this one :) 

And this is one of the reasons why, in most of the projects I maintain, I make sure to add the version number to certain files (README, CHANGELOG, others) so that I can perform a consistency check, during the release action, before creating the tag.

This reduces the chances (not to 0%, unfortunately) of publishing a wrong version number, because that would mean I'd made a mistake in several files...

**Comment by seebeen** [comment]
Ok, let's take it from the top.

>Well, there is a .githooks folder that aims to be used as a template for a commit-msg hook but we did not implemented any check to see if all commits respect the convention format.

This is easily done via husky and commitlint.

```bash
$ npm install husky --save-dev
$ npm pkg set scripts.prepare="husky install"
$ npm run prepare
```

**.husky/commit-msg**
```bash
#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

npx commitlint --edit $1
```

**.commitlintrc.json**
```json
{
  "extends": ["@commitlint/config-angular"],
  "rules": {
    "subject-case": [
      2,
      "always",
      ["sentence-case", "start-case", "pascal-case", "upper-case", "lower-case"]
    ],
    "type-enum": [
      2,
      "always",
      [
        "build",
        "chore",
        "ci",
        "docs",
        "feat",
        "fix",
        "perf",
        "refactor",
        "revert",
        "style",
        "test",
        "sample"
      ]
    ]
  }
}
```

Angular commit style enforced across all commits. Any contributor needs to follow the commit message standard. Enforced across forks, pull requests, and other workflows.

>Could be something interesting to work on... Should be possible to check commit message for a pull request with some GitHub action but I don't know how to prevent badly formatted message for a direct push, for example.

No need to check anything via actions. Everything is done by husky and the commit-msg hook. Fully enforceable.

This is easily implementable and works OOB for everyone, **everywhere**

> To determine the next version number , I base myself on https://semver.org/spec/v2.0.0.html

That is the semver spec, and is fully inline with semantic-release

>a) One of the most important points is to define, as explicitly as possible, what the public API is. In the case of this project, I've defined the [public API as being determined solely by the action.yaml file](https://github.com/ddev/github-action-add-on-test/blob/main/CHANGELOG.md#public-api).

The public API is the action file. Feature changes add the minor version, fixes add patch, and breaking changes are incrementing the major version.

> This means that we need to be able to consider only modifications to this file for release changes: we need to be able to exclude commits to files not covered by the public API (docs, .githooks and tests folder, etc.).

That's where the angular commit convention comes into play. Prefixes chore, docs, style, refactor will not make a new release. Commit type can be tweaked. So we can configure it any way we want. For example, maybe we want `refactor` to add the patch version. `semantic-release` can be configured that way

> b) It's true that with every release, I have to ask myself whether it's just a fix without breaking change (patch), a modification/addition without breaking change (minor), or a breaking change (major): it's a human decision, with all the risks that entails.

There is always a human factor. Yes, developer should know beforehand what he intends to do and to mark it as such.

> BUT, as far as I can read here: https://www.npmjs.com/package/semantic-release#how-does-it-work , semantic-release is using commit messages to determine the next release number. and these commit messages will have been written by humans ... For example, the responsibility for writing BREAKING CHANGE in the footer of the commit message will have been taken by a human; and I don't see much difference between that decision and the one I have to take now, every time I prepare to create a release.

The difference is - we switch over to git hooks and automated process, and we don't have to maintain separate actions for parsing the MD file, setting up changelog, etc. Everything is done automatically.
The decision what type of commit it is, and what's being coded is still on the developer.

There is just less maintanance all around. The release yml file has 150+ lines. Why should that be maintained, if it can be superceeded by 3 config files, and ready-made package which does the same (in a more consistent and reliable style)?

> To conclude, but this is more of a personal opinion, unfortunately too suggestive, I'm basing the changelog on this: https://keepachangelog.com/en/1.1.0/ and I like the guiding principle: "Changelogs are for humans, not machines.".
So I'm not too keen on seeing a list of commit messages in a changelog (a link with a version comparison seems sufficient for those interested in the details of each commit).

IMHO, changelogs are unecessary - that's what release notes are for. One for every separate release, but I think that's subjective, and I'm open for a middle ground, or to defer to your call.

All in all to summarize.

Implementing semantic-release flow will:
* Standardize deployments
* Standardize commit messages
* Reduce maintenance load on everyone
* Introduce easy updates, since it will automatically update vX and vX.Y tags so people can just use major tags.

Here is an example of an action I wrote which uses the semantic-release process 

https://github.com/better-php-actions/publish-composer-package

**Comment by julienloizelet** [comment]
Thanks for these explanations.

Now that I have all the facts, I've decided not to merge this PR.

The main reason is that I don't want version numbers to depend on commit messages.

Thanks again.

**Comment by seebeen** [comment]
No worries. I'll rollout my own 💪

**Comment by seebeen** [comment]
https://github.com/oblakstudio/action-test-ddev-addon

I've also implemented some reusable workflows which I will document further.

https://github.com/oblakstudio/public-workflows/

**Pull request closed without merging**
