### PR TITLE
Minor: Quiet down the brew installs

### PR DESCRIPTION
**Pull request by rfay**
## The Issue

I was just doing some work on an add-on and saw all the unuseful `brew install` output, suggest quieting it down.

### CODE REVIEW

**Comment by julienloizelet** [comment]
Hey @rfay,
thanks for the PR.

I asked my friend ChatGpt about this, and he suggests redirecting only stdout (i.e. >/dev/null) so that errors (and warnings) in stderr remain visible for debugging.

```
brew tap kaos/shell > /dev/null
brew install bats-core bats-file bats-assert bats-support jq mkcert yq > /dev/null
```

I didn't test the result, I'm not a stderr/stdout expert, and ChatGpt can be misleading, so what do yo think ?

Thanks

**Comment by rfay** [comment]
That's what this PR already implements, but it also redirects stderr.

**Comment by julienloizelet** [comment]
Shouldn't it be better to keep errors visible ? (for debugging purpose)
Thanks

**Comment by rfay** [comment]
I removed the stderr redirection, although my own experience is that those don't fail except when there's a network problem or a fundamental problem (like tap or package not being available any more). But there shouldn't be much if anything going to stderr anyway, so should be OK. Thanks so much for caring for this!

**Pull request merged**
