### PR TITLE
style: Fixed styling for commit message hook

### PR DESCRIPTION
**Pull request by seebeen**
## The Issue

Commit hook has styling issues regarding pipe handles and glob expansions

## How This PR Solves The Issue

Fixes style and logic errors in bash script

Line 8 - Fixes [SC2002](https://www.shellcheck.net/wiki/SC2002)
Line 18 - Fixes [SC2086](https://www.shellcheck.net/wiki/SC2086)

## Manual Testing Instructions

None

## Automated Testing Overview

None

## Related Issue Link(s)

N/A

## Release/Deployment Notes

No changes to release flow

### CODE REVIEW

**Comment by rfay** [comment]
When making a PR like this, make an effort to explain and show visually what you're doing. The title says "Fixed styling" but nothing in the PR says how, why, what was wrong with the styling, or how it's better now. Please edit to show these things, thanks!

**Comment by seebeen** [comment]
> When making a PR like this, make an effort to explain and show visually what you're doing. The title says "Fixed styling" but nothing in the PR says how, why, what was wrong with the styling, or how it's better now. Please edit to show these things, thanks!

Commit message is with the changes is not enough?

**Comment by rfay** [comment]
No, the commit message doesn't give any info at all, and the whole idea of a PR is to explain the purpose and result of a change. This is super important when working with teams, whether open-source or not. Good communication is more important even than good code when collaborating with others.

**Comment by julienloizelet** [comment]
Thanks !

**Pull request merged**
